services:
  - docker

env:
  global:
    - TEST_MODE=1
    - POSTGRES_HOSTNAME=127.0.0.1
    - POSTGRES_PORT=5439
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=test_database

os: linux

dist: focal

language: python

python:
  - '3.7'

branches:
  only:
    - master

install:
  - python -m pip install --no-cache-dir --upgrade pip wheel
  - python -m pip install --no-cache-dir -r requirements-versioned.txt
  - python -m pip install --no-cache-dir -r requirements-git.txt
  - python -m pip install --no-cache-dir -r requirements-dev.txt
  - python -m pip install -e .

before_script:
  - ./dev/start_local_dependencies.sh

script:
  - unit_tests
  - factory_tests
  - integration_tests

after_script:
  - ./dev/stop_local_dependencies.sh

notifications:
  email:
    - bifer@alea-soluciones.com
