# Postgresql
local_db_postgresql:
  image: postgres:13.3
  restart: always
  ports:
   - "${POSTGRES_PORT}:5432"
  environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
  volumes:
   - ./local_postgresql_configuration:/docker-entrypoint-initdb.d:ro
   - /etc/localtime:/etc/localtime:ro
